import type { Milestone } from "./types";

// Realistic sample data so the board looks lived-in on first load.
// Replace with a Supabase query once the milestones table exists.
export const SAMPLE_MILESTONES: Milestone[] = [
  {
    id: "m_001",
    title: "Discovery workshop sign-off",
    client: "Northwind Studio",
    clientInitials: "NS",
    amount: 3200,
    currency: "USD",
    dueDate: addDays(-2),
    column: "client_review",
    tags: [{ label: "Priority", tone: "priority" }, { label: "Strategy" }],
    progress: 80,
    description: "Final discovery deck + scope sign-off from stakeholders.",
  },
  {
    id: "m_002",
    title: "Homepage design v2",
    client: "Lumen Agency",
    clientInitials: "LA",
    amount: 4800,
    currency: "USD",
    dueDate: addDays(5),
    column: "in_progress",
    tags: [{ label: "Design", tone: "design" }],
    progress: 45,
  },
  {
    id: "m_003",
    title: "Brand guidelines PDF",
    client: "Fern & Co.",
    clientInitials: "FC",
    amount: 2400,
    currency: "USD",
    dueDate: addDays(12),
    column: "todo",
    tags: [{ label: "Design", tone: "design" }],
  },
  {
    id: "m_004",
    title: "Performance audit report",
    client: "Helix Labs",
    clientInitials: "HL",
    amount: 3200,
    currency: "USD",
    dueDate: addDays(1),
    column: "invoice_ready",
    tags: [{ label: "Research", tone: "research" }],
    progress: 100,
  },
  {
    id: "m_005",
    title: "Sprint 2 — checkout rebuild",
    client: "Atlas Co.",
    clientInitials: "AC",
    amount: 6000,
    currency: "USD",
    dueDate: addDays(9),
    column: "in_progress",
    tags: [{ label: "Dev", tone: "dev" }, { label: "Priority", tone: "priority" }],
    progress: 60,
  },
  {
    id: "m_006",
    title: "Migration to new CMS",
    client: "Northwind Studio",
    clientInitials: "NS",
    amount: 2400,
    currency: "USD",
    dueDate: addDays(-6),
    column: "invoice_sent",
    tags: [{ label: "Dev", tone: "dev" }],
  },
  {
    id: "m_007",
    title: "Logo refresh — final files",
    client: "Helix Labs",
    clientInitials: "HL",
    amount: 1800,
    currency: "USD",
    dueDate: addDays(-14),
    column: "paid",
    tags: [{ label: "Design", tone: "design" }],
    progress: 100,
  },
  {
    id: "m_008",
    title: "Q2 retainer — May",
    client: "Lumen Agency",
    clientInitials: "LA",
    amount: 5200,
    currency: "USD",
    dueDate: addDays(3),
    column: "invoice_sent",
    tags: [{ label: "Retainer" }],
  },
  {
    id: "m_009",
    title: "Content strategy doc",
    client: "Fern & Co.",
    clientInitials: "FC",
    amount: 1600,
    currency: "USD",
    dueDate: addDays(7),
    column: "todo",
    tags: [{ label: "Strategy" }],
  },
  {
    id: "m_010",
    title: "Onboarding email sequence",
    client: "Atlas Co.",
    clientInitials: "AC",
    amount: 2100,
    currency: "USD",
    dueDate: addDays(4),
    column: "client_review",
    tags: [{ label: "Copy" }],
    progress: 90,
  },
];

function addDays(days: number): string {
  const d = new Date();
  d.setDate(d.getDate() + days);
  return d.toISOString();
}
